# Generated by Django 6.0.4 on 2026-05-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.CharField(default='https://www.concretecms.com/application/files/9417/1778/2239/Restaurant_Websites.jpg', max_length=20)),
                ('cuisine', models.CharField(max_length=20)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
